kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-wait-for-db
data:
  wait-for-db.sh: |
    #!/bin/sh
    {{ printf "until nc -z -v -w30 %s %v" .Values.mysql.address .Values.mysql.port }}
    do
      echo "Waiting for database connection..."
      sleep 5
    done