apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-service-registry-properties
stringData:
  application.properties: |-
{{ list (merge .Values.serviceRegistry.properties (fromYaml (include "loadDBConnectionDetails" (dict "dot" . "component" .Values.serviceRegistry))) (fromYaml (include "loadCertificateDetails" (dict "component" .Values.serviceRegistry "mountpath" "/serviceregistry")))) "" | include "flattenYaml" | indent 4 }}