kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-service-registry-truststore
binaryData:
  truststore.p12: {{ printf "static/certificates/%s" .Values.serviceRegistry.truststore | .Files.Get | b64enc }}