kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-service-registry-keystore
binaryData:
  keystore.p12: {{ printf "static/certificates/%s" .Values.serviceRegistry.keystore | .Files.Get | b64enc }}