apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceRegistry.address }}
spec:
  selector:
    app: service-registry
  ports:
    - port: {{ .Values.serviceRegistry.port }}
      targetPort: {{ .Values.serviceRegistry.port }}
  type: ClusterIP