apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.orchestrator.address }}
spec:
  selector:
    app: orchestrator
  ports:
    - port: {{ .Values.orchestrator.port }}
      targetPort: {{ .Values.orchestrator.port }}
  type: ClusterIP