kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-orchestrator-keystore
binaryData:
  keystore.p12: {{ printf "static/certificates/%s" .Values.orchestrator.keystore | .Files.Get | b64enc }}