apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-authorization-properties
stringData:
  application.properties: |-
{{ list (merge .Values.authorization.properties (fromYaml (include "loadDBConnectionDetails" (dict "dot" . "component" .Values.serviceRegistry))) (fromYaml (include "loadCertificateDetails" (dict "component" .Values.authorization "mountpath" "/authorization"))) (fromYaml (include "loadSRDetails" .))) "" | include "flattenYaml" | indent 4 }}