kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-authorization-keystore
binaryData:
  keystore.p12: {{ printf "static/certificates/%s" .Values.authorization.keystore | .Files.Get | b64enc }}