kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-authorization-truststore
binaryData:
  truststore.p12: {{ printf "static/certificates/%s" .Values.authorization.truststore | .Files.Get | b64enc }}