apiVersion: v1
kind: Secret
metadata:
  name: adapter-keystore
type: Opaque
data:
  mqtt-keystore.p12: {{ .Files.Get "static/certs/mqtt-keystore.p12" | b64enc }}
  http-keystore.p12: {{ .Files.Get "static/certs/http-keystore.p12" | b64enc }}